-- Create statuses table
CREATE TABLE public.statuses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.statuses ENABLE ROW LEVEL SECURITY;

-- Create policies (assuming similar to categories)
CREATE POLICY "Enable read access for authenticated users" ON public.statuses
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert for authenticated users" ON public.statuses
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update for authenticated users" ON public.statuses
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Modify employees table
-- 1. Drop the old text status column (if exists)
ALTER TABLE public.employees DROP COLUMN IF EXISTS status;

-- 2. Drop the old foreign key constraint on room_id (if exists)
ALTER TABLE public.employees DROP CONSTRAINT IF EXISTS employees_room_id_fkey;

-- 3. Rename room_id to status_id
ALTER TABLE public.employees RENAME COLUMN room_id TO status_id;

-- 4. Add new foreign key constraint linking to statuses table
ALTER TABLE public.employees
    ADD CONSTRAINT employees_status_id_fkey
    FOREIGN KEY (status_id)
    REFERENCES public.statuses(id);
