CREATE TABLE IF NOT EXISTS funcionario_transferencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcionario_id BIGINT REFERENCES funcionarios(id),
  data_saida TIMESTAMP WITH TIME ZONE NOT NULL,
  data_chegada TIMESTAMP WITH TIME ZONE NOT NULL,
  unidade_atual_id BIGINT REFERENCES unidades(id),
  unidade_destino_id BIGINT REFERENCES unidades(id),
  usuario_id BIGINT REFERENCES usuarios(id),
  observacao TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
