-- Create table 'devolucoes'
create table if not exists devolucoes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    is_active boolean default true,
    date date not null,
    unit_id bigint references unidades(id),
    user_id bigint references usuarios(id),
    items jsonb default '[]'::jsonb,
    photos jsonb default '[]'::jsonb
);

-- RLS Policies for devolucoes (Basic: enable read for authenticated, insert for authenticated)
alter table devolucoes enable row level security;

create policy "Enable read access for authenticated users"
on devolucoes for select
to authenticated
using (true);

create policy "Enable insert access for authenticated users"
on devolucoes for insert
to authenticated
with check (true);

create policy "Enable update access for authenticated users"
on devolucoes for update
to authenticated
using (true);

-- Create storage bucket for 'devolucoes'
insert into storage.buckets (id, name, public)
values ('devolucoes', 'devolucoes', true)
on conflict (id) do nothing;

-- Storage policies
drop policy if exists "Authenticated users can upload images" on storage.objects;
drop policy if exists "Public Access" on storage.objects;

-- Note: We need to be careful not to drop policies for OTHER buckets if they share the same name/scope.
-- The previous migration `18_...` dropped global policies on storage.objects which might be risky if not scoped.
-- Checks:
-- Policy "Authenticated users can upload images" on storage.objects might be common.
-- Let's scope these policies specifically for this bucket or check bucket_id.

create policy "Give access to own folder 1bk578l_0" on storage.objects
  as permissive
  for insert
  to authenticated
  with check ((bucket_id = 'devolucoes'::text));

create policy "Give access to own folder 1bk578l_1" on storage.objects
  as permissive
  for select
  to public
  using ((bucket_id = 'devolucoes'::text));
